### ISSUE TITLE
Problems with Code

### ISSUE THREAD

**Issue by hylgisyg** [jvdkwast/PySEBS#1]
I research the SEBS model recently, and  find your code in this website, but I find some problems in your code, T0ta=Theta_s-Theta_a is always less than 0, that maybe let H  be negative. Is there something question in your code?

**Comment by qiyang77** [comment]
I have the same question. the H is small or negative in most situation even in the example files, which result the evaporative fraction is very high even at the fallow area. Something wrong?

**Comment by jvdkwast** [comment]
When we developed the model and found that H is negative we tried to find the cause. We found that this was the case in areas that experience the Oasis Effect. See also Figure 4.5 in my [PhD thesis](https://dspace.library.uu.nl/handle/1874/32313).
It might still be that equations/code are wrong. Feel free to correct and do a pull request. I'm not actively maintaining the model.
